version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
    - db-volume:/var/lib/postgresql/data

  api:
    image: gabrielnogueira7/clean-architecture-facens
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"
volumes:
  db-volume:
